### ISSUE TITLE
What changes need for Ubuntu18.10

### ISSUE THREAD

**Issue by DineshGuptaa** [blacktop/docker-elastic-stack#15]
Hi ,
Please guide me to make image for Ubuntu 18.10. I am getting issue with add user and installing software like libc6-compact and libzmq.

Getting issue to add user on Ubuntu. Command throws error.
 
Also, what is the purpose of using nodejs, apache2-utils. Without these  how to create images. 

Please help.

Thanks

**Comment by blacktop** [comment]
I apologize, however, issues are for bug reporting.  I wish you luck.
