### ISSUE TITLE
Enabling x-pack-reporting?

### ISSUE THREAD

**Issue by thlevy** [blacktop/docker-elastic-stack#16]
Hello all,
I would like to enable x-pack reporting when running elastic-stack (e.g with v6.6)
I tried setting it through an environment variable when running the docker image:
 `docker run -p 80:80 -p 9200:9200 --name elstack -e XPACK_MONITORING_ENABLED=true blacktop/elastic-stack:6.6`
But, unfortunately without any success!
Any way to do it without having to build my own image?
Thanks,
Thom

**Comment by blacktop** [comment]
So this image uses the OSS version to the ELK (elastic) Stack, which means it doesn't contain much of the X-Pack stuff.  If you want to play around with X-pack, you could try my other images or the official Elastic.co docker images.

Mine are here:

```bash
$ docker run -d --name elasticsearch -p 9200:9200 blacktop/elasticsearch:x-pack
$ docker run --init -d --name kibana --link elasticsearch -p 5601:5601 blacktop/kibana:x-pack
```

You can add your env var flags to those.
