### ISSUE TITLE
Question:  Need to make changes to the dockerfile and then copy to 

### ISSUE THREAD

**Issue by mark-hallman** [blacktop/docker-elastic-stack#17]
Hello Team Blacktop,

Full disclosure,  I have been working with docker for only a week.  That is 12 hours a day though.  So,  I could be asking for totally stupid questions.  

The elastic stack container is perfect for my needs.  I need the ability to spin up an ELK stack and load some data.  This is just for a demo on how digital forensics timelines could be loaded on the fly.  Loading these timelines into ELK is nothing new.  It is the ability to stand up the capability and have millions of row loaded int 15 min that it.  The test I have run show that it is easily doable. 

 What I need to do is to be able to put 2 - 3 small logstash config files in the container and have them be persistent.  I have experimented with volumes and they work great for having a connection to the host to get to the data that need to be loaded.  I don't know how to make volumes hold this data and still be able to distribute the volume along with the image.  

I was thinking that I could use the docker file to add those files into the image/container with COPY or ADD.  Would that be reasonable? Is there a location where the files could be placed and remain after a commit?

If I make changes like that to my local GitHub repo,  how can I push those back to my GitHub and eventually to my Docker Hub?

Is this even allowed?  Meaning would this violate your license?  

Any guidance is appreciated.  

Thanks
Mark Hallman

**Comment by blacktop** [comment]
You would create a new Dockerfile that started with:

```
FROM blacktop/elastic-stack:6.6

# Add custom logstash config
COPY config/logstash/conf.d/ /etc/logstash/conf.d/
COPY config/logstash/patterns/ /opt/logstash/patterns/
COPY config/logstash/logstash.yml /etc/logstash/
```

```bash
docker build -t mark-hallman/elastic-stack:6.6 .
docker push mark-hallman/elastic-stack:6.6
```
