### ISSUE TITLE
Incorrect version 7.3 deploy

### ISSUE THREAD

**Issue by yoburtu** [blacktop/docker-elastic-stack#20]
Hi,

I think last deploy has incorrect version:

blacktop/elastic-stack        7.3                 869MB

When I deploy the image, the version is 7.2.1:

		NODE_VERSION=10.15.2
		YARN_VERSION=1.13.0
		STACK=7.2.1
		JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk
		LS_SETTINGS_DIR=/etc/logstash
		ES_TMPDIR=/usr/share/elasticsearch/tmp
Volumes:	/etc/logstash/conf.d
		/etc/nginx
		/usr/share/elasticsearch/data

Best regards.

**Comment by blacktop** [comment]
I believe this is fixed now, can you please confirm?

**Comment by yoburtu** [comment]
Hi!, ok, now works!.

Thank you.

Best regards.
