### ISSUE TITLE
regarding the multi-node elastic using docker compose

### ISSUE THREAD

**Issue by mkscala** [blacktop/docker-elastic-stack#4]
I tried the docker-compose file to setup  multi-node containers. I i bring up the containers. How will access the kibana interface. I tried with the http://<digital-ocean-ip>/80 , but the kibana does not work.

**Comment by mkscala** [comment]
my ip address points to digital ocean instance. how will access the same from my local web browser ?
containers are up and running for me as well

**Comment by mkscala** [comment]
@blacktop , do you have an email id. I have another requirement on the same and i can email you

**Comment by blacktop** [comment]
It should be working now (as soon as the new version of `blacktop/elasticsearch` finishes building on the DockerHUB.  

For building a multi-node cluster on DigitalOcean you can do this - https://www.digitalocean.com/community/tutorials/how-to-set-up-a-production-elasticsearch-cluster-on-ubuntu-14-04

The important thing to notice is that the nodes need to think they are all on the same private network (and not be exposed to the public internet) although X-Pack will secure that for you, but you might need SSL.

Or you could set up a docker-swarm and run it that way.

Best of luck.

**Comment by mkscala** [comment]
Hi, I will try the same. when i meant multi-node it was multi-container micro service arch.
I have a private cloud with openstack and spinned up VM's using the same and executed your docker-compose file for elastic. in this case i tried use the Open stack VM <ip:address>:80, should we use any nginx reverse proxy to port 80 in public network ? for Kibana . I am guessing 
then below should work ?
With docker-engine : $(docker inspect -f '{{ .NetworkSettings.IPAddress }}' elstack)

**Comment by mkscala** [comment]
I have an project idea regarding the containerization technology since you have loads of experience in Docker/DevOps can we discuss about the same ?

**Comment by blacktop** [comment]
@mkscala I don't believe I have time to help with that.  

I have sooo many projects I am trying to work on now that I can barely keep up with.

**Comment by mkscala** [comment]
ok that's fine, if you are very busy then it is ok.
 It is an e-learning startup think about it and let me know the concept is Lab as as Service.
Or you can help on some doubts or you can support me as a Contributor.
