### ISSUE TITLE
elasticsearch exit accidentally

### ISSUE THREAD

**Issue by yafngzh** [blacktop/docker-elastic-stack#5]
env:
ubuntu 16.04 with vmware

the command was this
sudo docker run   -p 80:80 -p 9200:9200 blacktop/elastic-stack:5.1

 the result was:
![image](https://cloud.githubusercontent.com/assets/5991357/22582455/04670b4e-ea22-11e6-9a7a-07d3a96e0f1b.png)

and the kibana ui turned out:
![image](https://cloud.githubusercontent.com/assets/5991357/22582491/46bdadb8-ea22-11e6-9153-d3f71f959b91.png)

Could you help me to find out the cause?

**Comment by blacktop** [comment]
Can you try doing this before you start elastc-stack - 

```
echo "vm.max_map_count=262144" | sudo tee -a /etc/sysctl.conf
sudo sysctl -w vm.max_map_count=262144
```

**Comment by yafngzh** [comment]
This was already set. 
![image](https://cloud.githubusercontent.com/assets/5991357/22615878/82c8c73a-eada-11e6-8dd9-9ef8cf0847c4.png)

**Comment by blacktop** [comment]
Can you try:

```bash
$ sudo docker run -d --name elstack -p 80:80 -p 9200:9200 blacktop/elastic-stack:5.1
$ sudo docker exec elstack head -n30 /var/log/elasticsearch.stdout.log
```

**Comment by yafngzh** [comment]
yafngzh@ubuntu:~$ docker exec elstack_A head -n30 /var/log/elasticsearch.stdout.log
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 1798569984 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /tmp/hs_err_pid24.log
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 1798569984 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /tmp/hs_err_pid59.log
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 1798569984 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /tmp/hs_err_pid91.log
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 1798569984 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /tmp/hs_err_pid154.log
The reason seems to be not sufficient memory.
And it works well after I resize the memory of the VM. Thanks!
