### ISSUE TITLE
nginx problem in 5.4?

### ISSUE THREAD

**Issue by bachi76** [blacktop/docker-elastic-stack#9]
I've just updated to the 5.4 image, and nginx would not come up but complain:

```
Generating a 4086 bit RSA private key
......++
...........................................................................++
writing new private key to '/etc/nginx/ssl/kibana.key'
-----
rm: can't remove '/etc/nginx/conf.d/kibana.conf': No such file or directory
nginx: [emerg] a duplicate default server for [::]:80 in /etc/nginx/conf.d/ssl.kibana.conf:2
```
Seems port 80 was defined in both default.conf and kibana.conf. Deleting default.conf solved it (not sure if it's the right way though)

**Comment by blacktop** [comment]
That must have happened when I went from alpine:3.4 to alpine:3.5 as the base image.  Thank you for letting me know!!  Please feel free to re-open if the problem persists.
